### ISSUE TITLE
panda_gazebo_ros_control_plugin does not provide a working EffortJointInterface

### ISSUE THREAD

**Issue by smihael** [justagist/panda_simulator#25]
When I launch the simulator using [panda_world.launch](https://github.com/justagist/panda_simulator/blob/melodic-devel/panda_gazebo/launch/panda_world.launch) `panda_gazebo_ros_control_plugin` gets loaded instead of default gazebo `ros_control` plugin.

It seems to provide `EffortJointInterface` for ros_control plugins. Correct me if I'm wrong.

Let's say I have a plugin which uses this interface
`class TestController : public  controller_interface::MultiInterfaceController<hardware_interface::EffortJointInterface>`.
As usual I get the joint handles
`joint_handles[i] = effort_joint_interface->getHandle(joint_names[i]))`.  

They can be used for getting the for example the joint position with `joint_handles_[i].getPosition()`, but when I try to set effort with `joint_handles_[i].setCommand(tau[i])` the robot does not move.

The same code works on the real robot and in [an older revision of a similar project](https://github.com/erdalpekel/panda_simulation/tree/cde500f9ce233a5c0333798e1a8cdef370bcd97e).

For this reason I'm unable to run the simulator with a variety of other ros controllers.

If you load the following yaml to the paramter server:

```
panda_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    gains:
        panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
        panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
        panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
        panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
        panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
        panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

    constraints:
        goal_time: 2.0

    state_publish_rate: 25
```

And start `panda_arm_controller` with: `rosrun controller_manager spawner panda_arm_controller` 
you can use `rqt-joint-trajectory-controller` GUI to move the robot in erdalpekel's `panda_simulation`, but not in this project.
